
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Themes
frontend:
  themes: !include themes.yaml

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
# http:
#   base_url: example.duckdns.org:8123

# Text to speech
tts:
  - platform: google_translate
    language: 'el'

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# OASA
  - platform: oasa_telematics
    route_id: 1965
    stop_id: '090006'

# Yeelight
yeelight:
  devices:
    192.168.31.170:
      name: Entrance
      transition: 500
      save_on_change: true
    192.168.31.14:  
      name: Living Room 1
      transition: 500
      save_on_change: true
    192.168.31.65:
      name: Bedroom
      transition: 500
      save_on_change: true
    192.168.31.58:
      name: Living Room 2
      transition: 500
      save_on_change: true
    192.168.31.83:
      name: Kitchen
      transition: 500
      save_on_change: true

# Xiaomi Gateway
xiaomi_aqara:
  discovery_retry: 5
  gateways:
  - mac: !secret xiaomi_gateway1_mac
    key: !secret xiaomi_gateway1_key

# Xiaomi router
device_tracker:
  - platform: xiaomi
    host: 192.168.31.1
    password: !secret router_pass

# Xiaomi appliances
fan:
  - platform: xiaomi_miio
    host: 192.168.31.124
    token: !secret fan_token
    name: Fan
#    speed:
    
vacuum:
  - platform: xiaomi_miio
    host: 192.168.31.107
    token: !secret_vacuum_token
    name: Vacuum

remote:
  - platform: xiaomi_miio
    host: 192.168.31.226
    token: !secret remote_token
    name: IR Remote  
    
    # Vacuum workdays / holidays
binary_sensor:
  - platform: workday
    country: DE
    workdays: [tue, fri]
    excludes: [mon, wed, thu, sat, sun]
    